### ISSUE TITLE
Plugin install cannot find node on OSX 1.8.3

### ISSUE THREAD

**Issue by DanMacDonald** [raph-amiard/sublime-typescript#14]
The following message is displayed every time Sublime starts...

_The node executable hasn't been found, you might want to set it in your typescript settings by adding the "node_path" key_

I've added the node_path key to the typescript.sublime.settings file. Mine looks like this...

``` json
{
    "extensions": ["ts", "str"],
    "auto_complete": true,
    "node_path":"/usr/bin/local/node/node"
}
```

I've also added  the path to node  in my /etc/paths.d directory which exposes the path globally to all applications.

**Comment by DanMacDonald** [comment]
I was able to get this plugin to work, I was using the wrong path...  the working configuration is

``` json
{
    "node_path" : "/usr/bin/local/node"
}
```

**Comment by julianpinedayyz** [comment]
my settings (OSX 1.8.3):

{
    "extensions": ["ts", "str"],
    "auto_complete": false,
    "node_path": "/usr/local/bin/node"
}

Mine is working. Hope this helps.

J
