### ISSUE TITLE
Double quotes in reference paths

### ISSUE THREAD

**Issue by philllies** [raph-amiard/sublime-typescript#5]
Currently, the references are resolved with 

```
deps = re.findall("/// *<reference path *\='(.*?)'", content)
```

which does not match paths written in double quotes, such as:

```
/// <reference path="test.ts" />
```

**Comment by raph-amiard** [comment]
Hey thank you for the report, gonna fix that ASAP.

This was a quick and dirty solution, i'm gonna use the python xml module to parse that so as to be more robust.

**Comment by kube** [comment]
I did like this :

``` python
            # Find references with double quotes
            deps = re.findall('/// *<reference path *\="(.*?)"', content)
            # Find references with single quotes
            deps += re.findall("/// *<reference path *\='(.*?)'", content)
```

It seems to work for me, maybe there would be something more efficient.

**Comment by raph-amiard** [comment]
Ok it should be fixed now :)

**Comment by philllies** [comment]
@raph welcome :)

@kube
this is absolutely fine, but as you said, depending on the file size it might not be the most performant solution.

Using findall, you could also use this Regex pattern:

```
/// *<reference path *\=(?:\"|')(.*?)(?:\"|')
```

A little more compact. It also matches `/// <reference path='test.ts" />`, though, but since the compiler would complain about this anyway, I think it'll be fine.

**Comment by raph-amiard** [comment]
Hey phillies, i admit i avoided this solution because of mismatched brackets, the solution i used is similar, and avoids to scan the file two times.

**Comment by kube** [comment]
Bah I have to learn Regex Patterns, it is still chinese for me. :)
