### ISSUE TITLE
Getting the typescript source without git submodules

### ISSUE THREAD

**Issue by raph-amiard** [raph-amiard/sublime-typescript#6]
So that the package can be integrated into package manager, need to get rid of the git submodule.

Use a direct download link to the 0.8.2 release, so that i'm sure the plugin won't be broken by Typescript itself. [dl link](http://download-codeplex.sec.s-msft.com/Download/SourceControlFileDownload.ashx?ProjectName=typescript&changeSetId=0c05df1781d6)

At first launch, get the Typescript source if it ain't there, and unzip it, all using Python.

Maybe change the status message, since the loading is gonna take some more time.

**Comment by kube** [comment]
Nothing to do with it,, but Idk where to post it. You should vote on this :
http://sublimetext.userecho.com/topic/85632-need-the-completion-menu-to-be-wider/

You don't need to be logged in to vote, and it would be nice to have a customizable size for the autocompletion popup, which is actually hard-coded, and is sometimes unusable.

**Comment by raph-amiard** [comment]
Yes, already done that :) But since Sublime Text 3 beta is out, with an incompatible plugin API, don't get your hopes up. Any modification if it happens will make it into Sublime Text 3, and the plugin will still need to be ported to the new API.

**Comment by kube** [comment]
Yeah I saw that Sublime Text embeds python33.dll and not python26.dll like in Sublime Text 2. Do you think it is really hard to port from Python 2.6 to Python 3.3 ? (Not talking of the API).

**Comment by raph-amiard** [comment]
No it's easy, especially given the size of the plugin (rather small). I
expect the API to be more work.

I'm especially furious because i've spent hours going around sublime text's
stupid restrictions about api calls from threads, and now the API is thread
safe.

It's not a big problem in itself, and i'm happy the API evolves, but i'm
waiting to see if the guy releases Sublime Text 4 in 4 months, with another
40$ price increase, or not, before i commit to anything regarding this
plugin.

2013/2/4 kubekhrm notifications@github.com

> Yeah I saw that Sublime Text embeds python33.dll and not python26.dll like
> in Sublime Text 2. Do you think it is really hard to port from Python 2.6
> to Python 3.3 (Not talking of the API).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/raph-amiard/sublime-typescript/issues/6#issuecomment-13074041.

## 

Raphaël AMIARD

**Comment by FunkMonkey** [comment]
The issue concerning submodules in package control is also discussed [here](https://github.com/wbond/sublime_package_control/issues/326) and [here](https://github.com/wbond/sublime_package_control/issues/126).

I'd say you just create a new branch, which has the submodule included already and simply push every new release to that branch for package control, though I did not quite understand the solution using  a `.sublime-package` file, proposed by @wbond.

**Comment by raph-amiard** [comment]
Fixed, getting the zipfile in the installation procedure at first plugin launch
