### ISSUE TITLE
Typescript plugin still loading after closing file on Windows

### ISSUE THREAD

**Issue by kube** [raph-amiard/sublime-typescript#7]
When you open a file and don't wait for typescript to be completely loaded and you close the file, you still have the "Loading typescript plugin" in the status bar.

Is it possible to close the associated instance when you close the file ?

**Comment by kube** [comment]
http://www.sublimetext.com/docs/2/api_reference.html#sublime_plugin.EventListener
The API permits the on_close() event, and there is no event listener on this in your plugin.
It is a choice to keep the instance opened after closing the view ?

**Comment by raph-amiard** [comment]
Hey, sorry for the delay, no definitely not, it's a bug, i'll get around to fix that ASAP

**Comment by raph-amiard** [comment]
Should be fixed by now, feel free to reopen if you still experience that problem
