### ISSUE TITLE
AttributeError: 'module' object has no attribute 'STARTUPINFO'

### ISSUE THREAD

**Issue by beschulz** [raph-amiard/sublime-typescript#9]
```
Reloading plugin /Users/beschulz/Library/Application Support/Sublime Text 2/Packages/sublime-typescript/typescript.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./typescript.py", line 13, in <module>
    from core import project, install
  File "./core/install.py", line 13, in <module>
    startupinfo = subprocess.STARTUPINFO()
AttributeError: 'module' object has no attribute 'STARTUPINFO'
```

I'm on mac os x:
startup, version: 2220 osx x64 channel: dev

neither the subprocess module of the system installed python (Python 2.7.1) nor the one that can be imported via the sublime shell has STARTUPINFO as a member.

http://docs.python.org/2/library/subprocess.html states:
The STARTUPINFO class and following constants are only available on Windows.

Simply changing line 27 to `subprocess.call([node_path, "--help"])` worked after setting up an absolute path in typescript.sublime-settings

It would be really nice, if this plugin would work out of the box on Mac OS X

**Comment by kube** [comment]
There should a line before it :

``` python
startupinfo = None
if os.name == 'nt':
    startupinfo = subprocess.STARTUPINFO()
    startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
```

**Comment by beschulz** [comment]
Yes, this might help.

**Comment by raph-amiard** [comment]
Hey, sorry for this bug, i didn't have much time to maintain this the last couple of weeks. I just pushed a fix, tell me if it's working ok for you

**Comment by beschulz** [comment]
I'll check it out, as soon I i can - thanks for you effort.

2013/2/14 Raphaël AMIARD notifications@github.com
